#! /usr/bin/python

import json
import struct
import argparse

def header(outfile):
	hdr=struct.pack("IHHIIII", 0xa1b2c3d4,2,4,0,0,0xffff,1)
	outfile.write(hdr)

def convert(infile, outfile):
	fin=open(infile,"r")
	fout=open(outfile,"w")

	ehdr=struct.pack("6s6sH", '\xcc'*6, '\xbb'*6, 0xff7d)
	header(fout)
	for a in fin.readlines():
		b=json.loads(a)
		t=b['__REALTIME_TIMESTAMP']
		if '_SYSTEMD_UNIT' in b.keys():
			u=b['_SYSTEMD_UNIT']
		else:
			u="none"
		if 'SYSLOG_IDENTIFIER' in b.keys():
			sid=b['SYSLOG_IDENTIFIER']
		else:
			sid="none"

		tss=int(t[0:10])
		tsu=int(t[10:])
		log=str(b['MESSAGE'])

		#print tss,tsu,u,sid,log
		mesg=struct.pack("20s 20s H",str(u),str(sid),len(log))+log
		mlen=len(mesg)+len(ehdr)
		rec=struct.pack("IIII",tss,tsu,mlen,mlen)
		fout.write(rec)
		fout.write(ehdr)
		fout.write(mesg)

	fin.close()
	fout.close()


if __name__ == "__main__":
	parser=argparse.ArgumentParser(description="Convert journals in json format to PCAP")
	parser.add_argument('file', nargs='+', help="'journalctl -o json' output file")
	args=parser.parse_args()
	inputs=args.file
	outputs=["%s.pcap"%(x.replace('.json','')) for x in inputs] 
	for (x,y) in zip(inputs,outputs):
		convert(x,y)
	
