#! /usr/bin/python

import json
import argparse


def convert(infile, outfile):
	fin=open(infile,"r")
	fout=open(outfile,"w")

	for a in fin.readlines():
		b=json.loads(a)
		t=b['__REALTIME_TIMESTAMP']
		if '_SYSTEMD_UNIT' in b.keys():
			u=b['_SYSTEMD_UNIT']
		else:
			u="none"
		if 'SYSLOG_IDENTIFIER' in b.keys():
			sid=b['SYSLOG_IDENTIFIER']
		else:
			sid="none"

		tss=int(t[0:10])
		tsu=int(t[10:])
		log=str(b['MESSAGE'])

		mesg="%010d.%06d %-15.15s %-15.15s %s\n"%(tss,tsu,sid,u,log)
		#print tss,tsu,u,sid,log
		fout.write(mesg)

	fin.close()
	fout.close()


if __name__ == "__main__":
	parser=argparse.ArgumentParser(description="Convert journals in json format to regular logs")
	parser.add_argument('file', nargs='+', help="'journalctl -o json' output file")
	args=parser.parse_args()
	inputs=args.file
	outputs=["%s.txt"%(x.replace('.json','')) for x in inputs] 
	for (x,y) in zip(inputs,outputs):
		convert(x,y)
	
